name: example
description: Demonstrates the usage of the infinite list.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  very_good_infinite_list:
    path: ../

dev_dependencies:
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
