name: very_good_infinite_list
description: >-
  A library for easily displaying paginated data, created by Very Good Ventures.
  Great for activity feeds, news feeds, and more.
version: 0.9.0
repository: https://github.com/VeryGoodOpenSource/very_good_infinite_list
issue_tracker: https://github.com/VeryGoodOpenSource/very_good_infinite_list/issues
homepage: https://github.com/VeryGoodOpenSource/very_good_infinite_list
documentation: https://github.com/VeryGoodOpenSource/very_good_infinite_list
topics: [flutter, list-view, scroll, widgets]

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=7.0.0 <11.0.0"
